### ISSUE TITLE
Typo in field

### ISSUE THREAD

**Issue by kazkansouh** [cytopia/smtp-user-enum#12]
Hello,

I have just been trying out this project and noticed that it would fail on a retry. It looks like the following should have been `"from_email"` here instead of `"from"`.

https://github.com/cytopia/smtp-user-enum/blob/91f29ffe5dd5e051cc1cf3856d2beaf1eb32eaa8/smtp-user-enum#L550

Hope this is of some help.

**Comment by cytopia** [comment]
@kazkansouh I've addressed this in the PR a few hours ago: https://github.com/cytopia/smtp-user-enum/pull/11 (just fixed it the other way round)

Which is also related to this issue here: https://github.com/cytopia/smtp-user-enum/issues/10

@kazkansouh can you check if the PR works for you?

**Comment by cytopia** [comment]
Closing this one as a duplicated in favour of the issue which was there first: https://github.com/cytopia/smtp-user-enum/issues/10. Thanks for the hint :+1:

**Comment by kazkansouh** [comment]
My bad! I should have checked existing issues.

Thanks 🙂

**Comment by cytopia** [comment]
@kazkansouh can you give the PR a shot. I am unable to trigger a retry locally

**Comment by kazkansouh** [comment]
Sure, no problem. I'll give it a test in couple of hours.
